// ── Map Generator (Issue #269 — P3-2) ──
//
// AI-assisted generation of map regions from world description.
// Uses LLM prompt templates to produce structured region data
// (name, type, hierarchy, coordinates) that can be reviewed and saved.
//
// Architecture:
//   buildMapGeneratePrompt()   → returns system+user messages (caller sends to LLM)
//   parseMapGenerateResponse() → parses LLM JSON output into MapRegionCandidate[]
//   buildImageAnalyzePrompt()  → prompt for uploaded map image recognition
//
// The caller (API route) is responsible for the actual chatCompletion call.

import type { WorldConfig } from "../models/world-config.js";

// ── Public Types ──

/** A single map region candidate generated by AI */
export interface MapRegionCandidate {
  name: string;
  type: "大陆" | "国家" | "城市" | "地点";
  parentName: string | null;
  description: string;
  /** X coordinate as percentage (0-100) */
  x: number;
  /** Y coordinate as percentage (0-100) */
  y: number;
}

/** Result from image recognition AI call */
export interface ImageRegionResult {
  regions: MapRegionCandidate[];
  raw: string;
}

/** AI analysis result for an uploaded map image */
export interface ImageAnalysisResult {
  description: string;
  regions: MapRegionCandidate[];
  raw: string;
}

// ── Prompt Builders ──

/**
 * Build world context string from a WorldConfig.
 */
function formatWorldContext(world: WorldConfig): string {
  const parts: string[] = [];

  if (world.description) {
    parts.push(`## 世界观简介\n${world.description}\n`);
  }

  if (world.regions.length > 0) {
    parts.push(
      `## 已有地理区域\n${world.regions
        .map((r) => {
          const coords = r.x != null && r.y != null ? ` [坐标: (${r.x}, ${r.y})]` : "";
          return `- ${r.name}（${r.type}）: ${r.description}${coords}${r.parentId ? " [父区域ID: " + r.parentId + "]" : ""}`;
        })
        .join("\n")}\n`,
    );
  }

  if (world.settings.length > 0) {
    parts.push(
      `## 世界观设定\n${world.settings
        .map((s) => `- ${s.name}（${s.type}）: ${s.description}`)
        .join("\n")}\n`,
    );
  }

  if (world.institutions.length > 0) {
    parts.push(
      `## 组织势力\n${world.institutions
        .map((i) => `- ${i.name}（${i.type}）: ${i.description}`)
        .join("\n")}\n`,
    );
  }

  return parts.join("\n");
}

/**
 * Build system and user prompt messages for map (region) generation.
 */
export function buildMapGeneratePrompt(
  world: WorldConfig,
): { system: string; user: string } {
  const system = `你是一位资深世界观设计师和地图制图专家。你的任务是基于给定的世界观设定，生成一个完整的地理区域结构。

要求：
- 区域必须符合世界观的物理规则和风格
- 生成的区域类型包括：大陆、国家、城市、地点
- 需要建立层级关系（大陆 → 国家 → 城市/地点），通过 parentName 字段关联
- 坐标为百分比 (0-100)，表示在抽象地图上的相对位置
- 如果是已有区域的子区域，坐标应在父区域的范围内

请严格按照以下 JSON 格式返回（一个数组）：
\`\`\`json
[
  {
    "name": "区域名称",
    "type": "大陆|国家|城市|地点",
    "parentName": null,
    "description": "区域描述（包括地理特征、气候、文化等）",
    "x": 50,
    "y": 50
  }
]
\`\`\`

注意：
- parentName 为 null 表示顶层区域（大陆），子区域填入父区域的 name 值
- x, y 为 0-100 的整数，表示在抽象地图上的百分比位置
- 大陆应分布在地图各处，国家在大陆内部，城市/地点在国家内部
- 返回纯 JSON，不要 markdown 包装`;

  const user = `## 世界观: ${world.name}\n\n${formatWorldContext(world)}\n\n请基于以上世界观设定，生成完整的地理区域层级结构（大陆 → 国家 → 城市/地点），包含坐标信息。至少生成 3-8 个区域。`;

  return { system, user };
}

/**
 * Build prompt for analyzing an uploaded map image.
 * Tells the AI to recognize regions from the image and output structured data.
 */
export function buildImageAnalyzePrompt(): { system: string; user: string } {
  const system = `你是地图分析专家。分析用户上传的地图图片，识别其中的地理区域。

要求：
- 识别地图上的所有标注区域（国家、城市、地点等）
- 推断区域的类型（大陆、国家、城市、地点）
- 估算每个区域在地图上的位置百分比 (0-100)
- 如果明显存在层级关系，通过 parentName 字段表示

请严格按照以下 JSON 格式返回：
\`\`\`json
{
  "description": "对地图的整体描述",
  "regions": [
    {
      "name": "区域名称",
      "type": "大陆|国家|城市|地点",
      "parentName": null,
      "description": "区域描述",
      "x": 50,
      "y": 50
    }
  ]
}
\`\`\`

注意：
- 返回纯 JSON，不要 markdown 包装`;

  const user = "请分析这张地图图片，识别其中的地理区域并输出结构化数据。";
  return { system, user };
}

// ── JSON Extraction ──

/**
 * Extract and parse JSON from LLM response text.
 * Tries: direct parse → markdown code block → bare JSON object
 */
function extractJson(text: string): unknown {
  const trimmed = text.trim();

  // Try direct parse
  try {
    return JSON.parse(trimmed);
  } catch {
    // continue
  }

  // Try extracting from markdown code blocks
  const mdMatch = trimmed.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
  if (mdMatch) {
    try {
      return JSON.parse(mdMatch[1].trim());
    } catch {
      // continue
    }
  }

  // Try finding JSON array
  const arrayMatch = trimmed.match(/\[[\s\S]*\]/);
  if (arrayMatch) {
    try {
      return JSON.parse(arrayMatch[0]);
    } catch {
      // continue
    }
  }

  // Try finding JSON object
  const objMatch = trimmed.match(/\{[\s\S]*\}/);
  if (objMatch) {
    try {
      return JSON.parse(objMatch[0]);
    } catch {
      // continue
    }
  }

  return null;
}

// ── Response Parsers ──

/**
 * Parse LLM response text into MapRegionCandidate[].
 */
export function parseMapGenerateResponse(text: string, raw: string): MapRegionCandidate[] {
  const extracted = extractJson(text);
  if (!extracted) return [];

  // Direct array response
  if (Array.isArray(extracted)) {
    return extracted.map((item: Record<string, unknown>) => ({
      name: String(item.name ?? "未命名区域"),
      type: normalizeRegionType(item.type),
      parentName: item.parentName ? String(item.parentName) : null,
      description: String(item.description ?? ""),
      x: clampCoordinate(item.x),
      y: clampCoordinate(item.y),
    }));
  }

  // Wrapped object with "regions" key
  if (typeof extracted === "object" && extracted !== null) {
    const obj = extracted as Record<string, unknown>;
    if (Array.isArray(obj.regions)) {
      return obj.regions.map((item: Record<string, unknown>) => ({
        name: String(item.name ?? "未命名区域"),
        type: normalizeRegionType(item.type),
        parentName: item.parentName ? String(item.parentName) : null,
        description: String(item.description ?? ""),
        x: clampCoordinate(item.x),
        y: clampCoordinate(item.y),
      }));
    }
  }

  return [];
}

/**
 * Parse AI response for image analysis (wrapped object with description + regions).
 */
export function parseImageAnalysisResponse(
  text: string,
  raw: string,
): ImageAnalysisResult {
  const extracted = extractJson(text);

  const fallback = (): ImageAnalysisResult => ({
    description: "",
    regions: [],
    raw,
  });

  if (!extracted || typeof extracted !== "object") return fallback();

  const obj = extracted as Record<string, unknown>;

  // Try extracting regions from the result
  let regions: MapRegionCandidate[] = [];
  if (Array.isArray(obj.regions)) {
    regions = obj.regions.map((item: Record<string, unknown>) => ({
      name: String(item.name ?? "未命名区域"),
      type: normalizeRegionType(item.type),
      parentName: item.parentName ? String(item.parentName) : null,
      description: String(item.description ?? ""),
      x: clampCoordinate(item.x),
      y: clampCoordinate(item.y),
    }));
  }

  return {
    description: String(obj.description ?? ""),
    regions,
    raw,
  };
}

// ── Helpers ──

function normalizeRegionType(type: unknown): MapRegionCandidate["type"] {
  const validTypes: readonly MapRegionCandidate["type"][] = ["大陆", "国家", "城市", "地点"];
  const t = String(type ?? "地点");
  return validTypes.includes(t as MapRegionCandidate["type"])
    ? (t as MapRegionCandidate["type"])
    : "地点";
}

function clampCoordinate(value: unknown): number {
  const num = Number(value);
  if (Number.isNaN(num)) return 50;
  return Math.max(0, Math.min(100, Math.round(num)));
}

/**
 * Generate a unique ID for new regions.
 */
export function generateRegionId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `region_${ts}_${rand}`;
}
