import {
  CapabilitySkillManifestSchema,
  type CapabilitySkillManifest,
} from "./types.js";

const RAW_BUILTIN_CAPABILITY_SKILLS: CapabilitySkillManifest[] = [
  {
    id: "longform-writing",
    name: "Longform Writing",
    description: "Long-form serial novel creation: plan chapters, select story context, write, audit, revise, and preserve continuity.",
    whenToUse: "Use for long-form books, chapter planning, chapter continuation, audit repair, truth/state consistency, and author-intent driven writing.",
    triggers: [
      "长篇",
      "章节",
      "下一章",
      "续写",
      "审稿",
      "修稿",
      "伏笔",
      "author intent",
      "chapter",
      "write next",
      "longform",
    ],
    sessionKinds: ["book", "book-create"],
    promptPacks: [
      "longform.writer",
      "longform.reviser",
      "longform.auditor",
    ],
    toolHints: [
      "plan_chapter",
      "compose_chapter",
      "write_draft",
      "write_full_pipeline",
      "audit_chapter",
      "revise_chapter",
    ],
    contextNeeds: [
      {
        id: "author-intent",
        purpose: "Bind long-horizon user intent and prevent model defaults from overriding the book direction.",
        sources: ["story/author_intent.md"],
        tier: "protected",
        appliesTo: ["planner", "composer", "writer", "auditor", "reviser", "chat"],
        retrieval: "full",
      },
      {
        id: "current-focus",
        purpose: "Carry the next-chapter steering and short-horizon focus.",
        sources: ["story/current_focus.md"],
        tier: "protected",
        appliesTo: ["planner", "composer", "writer", "auditor", "reviser", "chat"],
        retrieval: "full",
      },
      {
        id: "chapter-memo",
        purpose: "Carry the planner's chapter-specific memo into writing and review.",
        sources: ["runtime/chapter_memo"],
        tier: "protected",
        appliesTo: ["composer", "writer", "auditor", "reviser"],
        retrieval: "full",
      },
      {
        id: "story-frame",
        purpose: "Preserve world rules, core conflict, tone, and non-negotiable canon anchors relevant to the task.",
        sources: ["story/outline/story_frame.md", "story/story_bible.md"],
        tier: "protected",
        appliesTo: ["planner", "composer", "writer", "auditor", "reviser", "chat"],
        retrieval: "sections",
      },
      {
        id: "volume-map",
        purpose: "Select the current arc/chapter planning section without injecting the entire long outline.",
        sources: ["story/outline/volume_map.md", "story/volume_outline.md"],
        tier: "protected",
        appliesTo: ["composer", "writer", "auditor", "reviser"],
        retrieval: "sections",
      },
      {
        id: "active-hooks",
        purpose: "Preserve active hook evidence and hook debt that the current chapter must honor.",
        sources: ["story/pending_hooks.md", "runtime/hook_debt"],
        tier: "protected",
        appliesTo: ["planner", "composer", "writer", "auditor", "reviser"],
        retrieval: "semantic",
      },
      {
        id: "episodic-memory",
        purpose: "Retrieve older chapter summaries, state facts, and volume summaries that are relevant but may be semantically compressed.",
        sources: ["story/chapter_summaries.md", "story/current_state.md", "story/volume_summaries.md"],
        tier: "compressible",
        appliesTo: ["composer", "writer", "auditor", "reviser"],
        retrieval: "semantic",
      },
    ],
    body: "",
    source: "builtin",
  },
  {
    id: "open-world-play",
    name: "Open World Play",
    description: "Open-world and branching interactive fiction: world contracts, character agents, time semantics, inventory/evidence/relation state, and scene rendering.",
    whenToUse: "Use for InkOS Play, open worlds, branching interaction, free actions, player persona, world state, character autonomy, and play illustrations.",
    triggers: [
      "开放世界",
      "分支互动",
      "互动世界",
      "自由行动",
      "角色agent",
      "世界契约",
      "视觉契约",
      "open world",
      "play",
      "interactive fiction",
    ],
    sessionKinds: ["play"],
    promptPacks: [
      "play.start",
      "play.mutator",
      "play.renderer",
      "play.reconciler",
      "play.image",
    ],
    toolHints: [
      "play_start",
      "play_step",
      "generate_play_image",
    ],
    contextNeeds: [
      {
        id: "world-contract",
        purpose: "Bind the world rules, time semantics, taboos, and durable play constraints confirmed by the user.",
        sources: ["skills/world-contract.md", "world/contract.md", "state/world.md"],
        tier: "protected",
        appliesTo: ["play_start", "play_step", "mutator", "renderer"],
        retrieval: "full",
      },
      {
        id: "player-persona",
        purpose: "Preserve the player's identity, constraints, viewpoint, and current goals.",
        sources: ["skills/player-persona.md", "state/player.md"],
        tier: "protected",
        appliesTo: ["play_start", "play_step", "mutator", "renderer"],
        retrieval: "full",
      },
      {
        id: "active-play-state",
        purpose: "Carry active scene, character, relationship, inventory, evidence, and time state.",
        sources: ["state.md", "scene.md", "graph.db", "graph.json"],
        tier: "protected",
        appliesTo: ["play_step", "mutator", "renderer", "reconciler"],
        retrieval: "semantic",
      },
      {
        id: "visual-contract",
        purpose: "Use user-confirmed visual semantics for scene, character, item, and evidence images without inventing game UI frames.",
        sources: ["skills/visual-contract.md", "image-settings.json", "images/manifest.json"],
        tier: "protected",
        appliesTo: ["image", "renderer"],
        retrieval: "full",
      },
      {
        id: "old-events",
        purpose: "Recall older play events only when relevant; they may be summarized to keep the active scene responsive.",
        sources: ["events.jsonl", "transcript.md"],
        tier: "compressible",
        appliesTo: ["play_step", "renderer"],
        retrieval: "semantic",
      },
    ],
    body: "",
    source: "builtin",
  },
  {
    id: "interactive-film-authoring",
    name: "Interactive Film Authoring",
    description: "Interactive film and game-like drama authoring: story graph, variables, endings, script, storyboard, image prompts, and export packages.",
    whenToUse: "Use for interactive-film projects, branching drama, visual novel style scripts, variables/flags, multiple endings, storyboards, and image asset planning.",
    triggers: [
      "互动影游",
      "互动剧",
      "分支剧情",
      "变量旗标",
      "多结局",
      "剧情图谱",
      "分镜",
      "interactive film",
      "branching drama",
      "story graph",
      "storyboard",
    ],
    sessionKinds: ["interactive-film", "interactive-film-authoring"],
    promptPacks: [
      "interactive-film.script",
      "interactive-film.storyboard",
      "interactive-film.story-graph",
      "interactive-film.image-plan",
    ],
    toolHints: [
      "interactive_film_create",
      "set_world_anchor",
      "add_variable",
      "upsert_characters",
      "fill_node",
      "revise_node",
      "generate_node_image",
    ],
    contextNeeds: [
      {
        id: "story-graph",
        purpose: "Preserve canonical node topology, choices, variables, endings, and current authoring target.",
        sources: ["story-graph.json"],
        tier: "protected",
        appliesTo: ["authoring", "script", "storyboard", "image"],
        retrieval: "full",
      },
      {
        id: "current-node",
        purpose: "Focus generation and edits on the current node while respecting graph topology.",
        sources: ["story-graph.json#current-node"],
        tier: "protected",
        appliesTo: ["fill_node", "revise_node", "image"],
        retrieval: "sections",
      },
      {
        id: "character-voices",
        purpose: "Preserve character motivations and voice profiles across nodes.",
        sources: ["skills/character-voices.md", "story-graph.json#characters", "memory.db"],
        tier: "protected",
        appliesTo: ["script", "fill_node", "revise_node"],
        retrieval: "semantic",
      },
      {
        id: "visual-style",
        purpose: "Preserve visual style, image prompt conventions, aspect ratio, and asset constraints for node images.",
        sources: ["skills/visual-style.md", "image-prompts.md", "assets.json"],
        tier: "protected",
        appliesTo: ["image", "storyboard"],
        retrieval: "full",
      },
      {
        id: "previous-node-summaries",
        purpose: "Recall previous branch beats without injecting the entire script into every node-level edit.",
        sources: ["script.md", "storyboard.md", "story-tree.md"],
        tier: "compressible",
        appliesTo: ["fill_node", "revise_node", "storyboard"],
        retrieval: "semantic",
      },
    ],
    body: "",
    source: "builtin",
  },
];

export const BUILTIN_CAPABILITY_SKILLS: ReadonlyArray<CapabilitySkillManifest> =
  RAW_BUILTIN_CAPABILITY_SKILLS.map((skill) => CapabilitySkillManifestSchema.parse(skill));
